version: "3"
services:
  #### Redis ####
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      # - "${REDIS_PORTS}"
    expose:
      - 6379
    networks:
      - network
  #### RedisProxyServer ####
  redis_proxy:
    container_name: redis_proxy
    build:
      context: .
      dockerfile: ./RedisProxy/Dockerfile
    ports:
      - "8080:8080"
      - "8124:8124"
    expose:
      - 8080
      - 8124
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-1}
      - CACHE_CAPACITY=${CACHE_CAPACITY:-4}
    # env_file:
    #   - .env
    networks:
      - network
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  network: