version: "3"
######## Bridge network shared by each container ########
networks:
  network:

services:
  #### Redis ####
  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORTS:-6379:6379}
    networks:
      - network

  #### RedisProxyServer ####
  redis_proxy:
    container_name: redis_proxy
    build:
      context: .
      dockerfile: ./RedisProxy/Dockerfile
    ports:
      - "8080:8080"
      - "8124:8124"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-1}
      - CACHE_CAPACITY=${CACHE_CAPACITY:-4}
      - MAX_CONCURRENT_HANDLERS=${MAX_CONCURRENT_HANDLERS:-12}
    networks:
      - network
    command: "java -jar /server.jar"

  #### RedisProxyIntegrationTests ####
  integration_tests:
    container_name: integration_tests
    build:
      context: .
      dockerfile: ./RedisProxyIntegrationTests/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - redis_proxy
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-10000}
      - CACHE_CAPACITY=${CACHE_CAPACITY:-4}
    networks:
      - network
    command: mvn test