version: "3"
######## Bridge network shared by each container ########
networks:
  network:

services:
  #### Redis ####
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      # TODO: make this like the environ variables
      # - "${REDIS_PORTS}"
    expose:
      - 6379
    networks:
      - network

  #### RedisProxyServer ####
  redis_proxy:
    container_name: redis_proxy
    build:
      context: .
      dockerfile: ./RedisProxy/Dockerfile
    ports:
      - "8080:8080"
      - "8124:8124"
    expose:
      - 8080
      - 8124
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-1}
      - CACHE_CAPACITY=${CACHE_CAPACITY:-4}
    # env_file:
    #   - .env
    networks:
      - network
    # image: maven:3
    # stop_signal: SIGKILL
    # stdin_open: true
    # tty: true
    # working_dir: $PWD
    # volumes:
    #   - $PWD:$PWD
    #   - /var/run/docker.sock:/var/run/docker.sock
      # Maven cache (optional)
      # - ~/.m2:/root/.m2
    # command: "java -jar /server.jar"
    command: "java -jar /server.jar"

  #### RedisProxyIntegrationTests ####
  integration_tests:
    container_name: integration_tests
    build:
      context: .
      dockerfile: ./RedisProxyIntegrationTests/Dockerfile
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - redis
      - redis_proxy
    environment:
      # TODO: can I just change "localhost" to redis_proxy
      - REDIS_PROXY_HOST=${REDIS_PROXY_HOST:-redis_proxy}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - CACHE_EXPIRY=${CACHE_EXPIRY:-1}
      - CACHE_CAPACITY=${CACHE_CAPACITY:-4}
    # env_file:
    #   - .env
    networks:
      - network
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      # Maven cache (optional)
      - ~/.m2:/root/.m2
    command: mvn test